server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    resolver 127.0.0.11 valid=5s ipv6=off;
    resolver_timeout 2s;
    proxy_connect_timeout 2s;
    proxy_read_timeout 3s;
    proxy_send_timeout 3s;

    location /api/graos/ {
        set $upstream graos-service:8000;
        rewrite ^/api/graos/(.*)$ /$1 break;
        proxy_pass http://$upstream;
    }
    location /api/metodos/ {
        set $upstream metodo-service:8000;
        rewrite ^/api/metodos/(.*)$ /$1 break;
        proxy_pass http://$upstream;
    }
    location /api/degustacoes/ {
        set $upstream degustacao-service:8000;
        rewrite ^/api/degustacoes/(.*)$ /$1 break;
        proxy_pass http://$upstream;
    }
    location /api/chat/ {
        set $upstream chat:8000;
        rewrite ^/api/chat/(.*)$ /$1 break;
        proxy_pass http://$upstream;
        proxy_read_timeout 95s;
    }
    location / { try_files $uri $uri/ =404; }
}
